### ISSUE TITLE
[minecraft] Evaluate JVM G1 Garbage Collector

### ISSUE THREAD

**Issue by zaquestion** [itzg/dockerfiles#126]
Would you mind switching or maintaining a second `dockerfile` using the jdk image on https://hub.docker.com/r/library/openjdk/tags/

Its _only_ 100MB more space, my vote would be to just cut over, but a seperate tag/dockerfile would be excellent

ref on jvm options that require jdk
http://gaming.stackexchange.com/questions/104527/how-can-i-run-a-minecraft-server-on-multiple-cpu-cores

Only requires changing `jre` to `jdk` here: https://github.com/itzg/dockerfiles/blob/master/minecraft-server/Dockerfile#L1

FWIW, I built my own version of this locally and was able to start up both a vanilla and forge based server

**Comment by itzg** [comment]
I agree that's a reasonable increase in size; however, having worked with Java for many years now I am quite certain the JDK doesn't add any JVM options beyond the JRE. The [official faq](https://www.java.com/en/download/faq/techinfo.xml) confirms my understanding that the JDK differs by including development-time tools such as `javac`, `jar`, etc.

I did notice that I haven't enabled the [G1 garbage collector](https://www.java.com/en/download/faq/techinfo.xml) which would provide much more improvements for large memory, multi-core hosting of Minecraft.

I can go ahead and make the G1 GC change, but let me know if you can find any official docs on multi-core differences of the JDK vs JRE.

**Comment by itzg** [comment]
@zaquestion , can you give the image I just pushed, `50e62877c056`, a try? I'm also going to stress test it tomorrow on my dual CPU, quad core system.

**Comment by itzg** [comment]
...I also introduced a new `-e MAX_MEMORY=...` option to make it easier to bump up the JVM memory limit.

**Comment by zaquestion** [comment]
@itzg I'm trying this out, so far so good, I also used your `MAX_MEMORY` option. I am seeing a lot more JVM memory getting used and a lot less garbage collects which seems nice.

Here is the config
```
  infinity:
    image: itzg/minecraft-server
    restart: always
    volumes:
      - /minecraft_infinity:/data
      - /storage/minecraft_infinity/plugins/dynmap:/data/plugins/dynmap
    ports:
      - 25565:25565
      - 80:8123
      - 9225:9225
    environment:
      - TYPE=SPIGOT
      - CONSOLE=false
      - EULA=TRUE
      - LEVEL_TYPE=LARGEBIOMES
      - PVP=TRUE
      - VIEW_DISTANCE=16
      - MAX_BUILD_HEIGHT=512
      - MAX_PLAYERS=100
      - OPS=zaquestion
      - DIFFICULTY=hard
      - MAX_MEMORY=8G
```
