### ISSUE TITLE
[Minecraft] Failed to load native library:sqlite-3.15.1

### ISSUE THREAD

**Issue by sladkoff** [itzg/dockerfiles#133]
I have issues with Bukkit + SQLite after upgrading to the Alpine based image. 

During startup this happens:
```
[WARN]: Failed to load native library:sqlite-3.15.1-6f7bc1af-1dba-4675-84c7-aaf90017dff0-libsqlitejdbc.so. osinfo: Linux/x86_64
[WARN]: java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.15.1-6f7bc1af-1dba-4675-84c7-aaf90017dff0-libsqlitejdbc.so: Error relocating /tmp/sqlite-3.15.1-6f7bc1af-1dba-4675-84c7-aaf90017dff0-libsqlitejdbc.so: __isnan: symbol not found
```

Due to the above problems, an error similar to the following happens when attempting to load Bukkit plugins that rely on sqlite (plugins aren't loaded, but server starts):
```
[INFO]: [CoreProtect] Enabling CoreProtect v2.14.2
[ERROR]: Error occurred while enabling CoreProtect v2.14.2
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
```

My stack file looks something like this:
```
minecraft-server:
  environment:
    - TYPE=BUKKIT/SPIGOT
  image: 'itzg/minecraft-server:latest'
  ports:
    - '25565:25565'
    - '25575:25575'
  volumes:
    - '/minecraft/data:/data'
```

I've downgraded to the debian image for now.

Here are some links that might be related (didn't check thoroughly, sorry):
https://github.com/xerial/sqlite-jdbc/issues/197
https://github.com/xerial/sqlite-jdbc/issues/97
https://hub.spigotmc.org/jira/browse/SPIGOT-2853

I can provide more info if needed.
