### ISSUE TITLE
Passing "-D" command line params to Minecraft?

### ISSUE THREAD

**Issue by smxsm** [itzg/dockerfiles#177]
Hi,
I have a problem starting a FORGE server with a map containing "invalid" objects caused by a missing mod (which I can't install since it is crashing the server). Minecraft is telling me during startup (and then hangs):

> Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

But I can't find a way to pass that option via Docker ENV vars to Minecraft and I also cannot enter any commands while docker is starting the server... any idea how to do this? Thanks! :)

Guess you'd have to add it to the image to support this, see e.g. https://stackoverflow.com/questions/33408626/how-to-pass-system-property-to-docker-containers

**Comment by itzg** [comment]
@smxsm sorry the delay on responding. Apparently I forgot to document it, but you can pass -D's via the `JVM_OPTS`, such as `-e "JVM_OPTS=-Dfml.queryResult=confirm"`.

Let me know if that does work for you and I'll also update the README.

**Comment by HashDot** [comment]
I've tested the JVM_OPTS to use a http proxy for minecraft. It doesnt work. :(

The proxy works fine with docker, apt, so on ...

Here my docker-compose (docker swarm):

```
version: "3.3"

networks:
  minecraft:
    driver: overlay

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    networks:
      - minecraft
    volumes:
      - /bricks/minecraft:/data
    environment:
      - TYPE=SPIGOT
      - VERSION=1.12.2
      - EULA=TRUE
      - SPIGOT_DOWNLOAD_URL=https://cdn.getbukkit.org/spigot/spigot-1.12.2.jar
      - JVM_OPTS=-Dhttp.proxyHost=xx.xx.xx.xx -Dhttp.proxyPort=8888 -Dhttps.proxyHost=xx.xx.xx.xx -Dhttps.proxyPort=8888
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
```
