### ISSUE TITLE
Server not following FORGEVERSION, MC 12.2

### ISSUE THREAD

**Issue by chris42** [itzg/dockerfiles#211]
I just figured, that the server in the image is not following the defined Forge version.
In my docker-compose I defined: 
`FORGEVERSION: 14.23.3.2655`

However in the logs it shows (and not functioning mods confirm), that Version "14.23.2.2632" is used:
`Apr 16 02:59:30 server minecraft-server[659]: [00:59:30] [main/INFO] [FML]: Forge Mod Loader version 14.23.2.2632 for Minecraft 1.12.2 loading`

Strangely it seems to download and install it, as I can find the versions corresponding .jar. However it does not use it.

Any clue what this could be?

**Comment by chris42** [comment]
Sure, here is the complete docker-compose definition.

```
version: "3.2"
services:

    minecraft-server:
        image: itzg/minecraft-server
        container_name: minecraft-server
        hostname: server
        healthcheck:
          disable: true
        ports:
        - "25565:25565"
        environment:
          EULA: 'TRUE'
          UID: 1001
          GID: 1002
          VERSION: 1.12.2
          TYPE: FORGE
          FORGEVERSION: 14.23.3.2655
          MEMORY: 8G
          PERMGEN_SIZE: 512M
          ONLINE_MODE: 'FALSE'
          OPS: User1
          JVM_XX_OPTS: '-XX:SurvivorRatio=2 -XX:+DisableExplicitGC -d64 -XX:+UseConcMarkSweepGC -XX:+AggressiveOpts -Dfml.queryResult=confirm'
        volumes:
        - type: bind
          source: /srv/var/local/minecraft
          target: /data
        logging:
          driver: syslog
          options:
            tag: "{{.Name}}"
```

BTW, feel free to use it as an example in your documentation. I can also do a commented version on each line. Just let me know.
