### ISSUE TITLE
Error: Invalid or corrupt jarfile craftbukkit_server.jar

### ISSUE THREAD

**Issue by billw2012** [itzg/dockerfiles#242]
Using this docker-compose.yml:
````
minecraft-server:
  ports:
    - "25566:25565"
  volumes:
    - "./data:/data"
  environment:
    EULA: "TRUE"
    ENABLE_RCON: "true"
    GENERATE_STRUCTURES: "true"
    DIFFICULTY: "normal"
    ALLOW_NETHER: "true"
    SNOOPER_ENABLED: "false"
    VIEW_DISTANCE: "6"
    MODE: "survival"
    SEED: "2"
    LEVEL: "first"
    TYPE: "BUKKIT"
    VERSION: "1.8"
  
  image: itzg/minecraft-server

  container_name: mc

  tty: true
  stdin_open: true
  restart: always
````

I have deleted and recreated multiple times, always the same result.
