### ISSUE TITLE
Passing custom arguments to minecraft

### ISSUE THREAD

**Issue by Marfjeh** [itzg/dockerfiles#252]
Is there a way to pass arguments such as `--forceUpgrade` to the docker container?

This argument causes to force the server to upgrade the world, and not on the fly.

**Comment by itzg** [comment]
Don’t worry at all. I’m glad to hear it worked for you.

**Comment by quiquelhappy** [comment]
Hello!
How should I do this using docker-compose?

**Comment by itzg** [comment]
@quiquelhappy you'll pass those with the confusingly named `command` attribute:

https://docs.docker.com/compose/compose-file/#command

**Comment by quiquelhappy** [comment]
I'm guessing something like this should work then:
```
  cool1:
    image: itzg/minecraft-server:adopt11
    command: ["--forceUpgrade"]
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 16G
        reservations:
          cpus: "2.0"
          memory: 16G
    environment:
      SPIGOT_DOWNLOAD_URL: https://soupuwu.nl/dl/spigot16.jar
      # FORCE_REDOWNLOAD: "true"
      ENABLE_RCON: "false"
      EULA: "true"
      TYPE: "SPIGOT"
      VERSION: "1.16.1"
      SERVER_NAME: "cool1"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 200
      VIEW_DISTANCE: 8
      ONLINE_MODE: "false"
      MEMORY: 16G
      MODE: "survival"
    restart: always
    ports:
      - 127.0.0.1:25001:25565
      - 15001:8193
    volumes:
      - /home/quiquelhappy/purevanilla.co/servers/cool/:/data
    container_name: cool1
```
