### ISSUE TITLE
Cloning existing world using -e WORLDS not behaving as expected

### ISSUE THREAD

**Issue by ThaChillera** [itzg/dockerfiles#308]
I'm trying to clone my existing world into this new container. directory layout:

docker-compose.yml
minecraft/
&nbsp;&nbsp;vanilla/
&nbsp;&nbsp;&nbsp;&nbsp;world/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;level.dat
&nbsp;&nbsp;&nbsp;&nbsp;minecraft server jar etc

my docker-compose file is:

        mc_vanilla:
                container_name: mc_vanilla
                image: itzg/minecraft-server
                restart: unless-stopped
                ports:
                        - "25565:25565"
                volumes:
                        - "mc_vanilla:/data"
                        - "./minecraft:/worlds:ro"
                environment:
                        EULA: "TRUE"
                        VERSION: "1.13.2"
                        WORLD: "/worlds"

Two issues, probably connected:
1. When running this, the log states "cloning world directory from /worlds ...". However, the folder 'vanilla' isn't present in the /data/world folder, even though [line 39](https://github.com/itzg/dockerfiles/blob/master/minecraft-server/start-finalSetup01World) says the entire contents of the worlds folder is copied over to, in this case, /data/world.
2. When adding an "WORLD" ENV path larger than 1 layer (eg /worlds/vanilla), it reports "Invalid URL given for world: Must be HTTP or HTTPS and a ZIP file", even though the given path is perfectly valid.

I tried adding the contents of ./minecraft/vanilla/world to ./minecraft, in case the world generator overwrote the contents of /data/world (doubt it), but this didn't change anything.

Help would be appreciated!

**Comment by itzg** [comment]
Hmm, using

```
   WORLD: "/worlds/vanilla"
```

should have been the right approach; however, it must be hitting [line 44](https://github.com/itzg/dockerfiles/blob/master/minecraft-server/start-finalSetup01World#L44) which means the `/worlds` volume mount didn't work as expected.

I'll try to recreate this myself too.

**Comment by ThaChillera** [comment]
Did you manage to find the time to test this yet?

**Comment by itzg** [comment]
This is what worked for me. For testing sake, I started up a container and then stopped it to create a world data area:

```
docker run -it --rm -e EULA=TRUE -e VERSION=1.13.2 -v $PWD/data:/data itzg/minecraft-server
```

After stopping that, I transplanted the world directory from into a "worlds" area:

```
mkdir worlds
mv data/world worlds/vanilla
```

Then in the current directory I used this `docker-compose.yml` file:
```yaml
version: '3.4'
services:
  mc_vanilla:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - mc_vanilla:/data
      - ./worlds:/worlds
    environment:
      EULA: "TRUE"
      VERSION: "1.13.2"
      WORLD: /worlds/vanilla
volumes:
  mc_vanilla: {}
```
