### ISSUE TITLE
the-1710-pack

### ISSUE THREAD

**Issue by avendretter** [itzg/dockerfiles#338]
Hey ho,

long time no see ;)

well this time a similar issue... I am trying to get the modpack the-1710-pack to work.
Since I got the TPPI-Modpack to work with the FTB-settings, so I tried the same with this one:
https://www.technicpack.net/modpack/the-1710-pack.453902

This is my docker-compose.yml:
```
version: '3'
services:
  minecraft:
    container_name: mc_mod
    image: itzg/minecraft-server
    environment:
      - EULA=TRUE
      - TYPE=FTB
      - FTB_SERVER_MOD=http://solder.endermedia.com/repository/downloads/the-1710-pack/the-1710-pack_0.9.8.zip
      - FTB_LEGACYJAVAFIXER=true
    volumes:
      - /home/nebukadnezar/data/games/minecraft_mods/the-1710/data:/data
    ports:
      - 25566:25565
    tty: true
    stdin_open: true
```

the point is, that the container is just suddenly restarting while loading ...
I have no idea why. I attached to logs, cause they are so f* long *-.-

[the-1710-pack.log](https://github.com/itzg/dockerfiles/files/3293534/the-1710-pack.log)

maybe its a naming thing. I dont know.
Idea:
add a servertype "technicpack" which just unpacked and run the prepacked server.jar

Best regards,
Avendretter
