### ISSUE TITLE
[minecraft] Error: Invalid or corrupt jarfile minecraft_server.1.9.jar

### ISSUE THREAD

**Issue by embik** [itzg/dockerfiles#63]
I'm trying to create a docker container based on itzg/minecraft-server. Unfortunately, starting the docker container fails with the error message `Error: Invalid or corrupt jarfile minecraft_server.1.9.jar`. I'm not sure if this is an issue with the image or with some kind of configuration I messed up, but I'm glad for any help. Relevant files and logs are attached:

**docker-compose.yml**
```
minecraft-server:
  ports:
    - "25565:25565"
  volumes:
    - /var/docker/minecraft/server/data:/data
  environment:
    EULA: "TRUE"
  image: itzg/minecraft-server
  container_name: mc
```

**running docker-compose up**
```
[admin@server server]$ sudo docker-compose up
Creating mc
Attaching to mc
mc | usermod: no changes
mc | ...switching to user 'minecraft'
mc | Checking version information.
mc | --2016-03-11 18:47:47--  https://s3.amazonaws.com/Minecraft.Download/versions/versions.json
mc | Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.12.248
mc | Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.12.248|:443... connected.
mc | HTTP request sent, awaiting response... 200 OK
mc | Length: 23637 (23K) [application/octet-stream]
mc | Saving to: ‘STDOUT’
mc | 
mc |      0K .......... .......... ...                             100%  249K=0.09s
mc | 
mc | 2016-03-11 18:47:48 (249 KB/s) - written to stdout [23637/23637]
mc | 
mc | Checking type information.
mc | Error: Invalid or corrupt jarfile minecraft_server.1.9.jar
mc exited with code 1
```
