### ISSUE TITLE
Updating Ops/Whitelist

### ISSUE THREAD

**Issue by larrywright** [itzg/dockerfiles#89]
Currently there doesn't seem to be a way to update the whitelist of users by way of the WHITELIST environment variable - if the white-list.txt.converted file exists, the value of the WHITELIST environment variable is ignored. Is the intention that that variable is only for the initial setup, and then the whitelist.json file is maintained by hand after that?

Also, I've noticed that if you use either the WHITELIST or OPS environment variables, the first time the server is launched, they don't take effect. You have to shut down the server and start it back up and then the whitelisted users are able to log in. Is this a known issue?

**Comment by itzg** [comment]
Yes, @larrywright , as you speculated the environment variables are only intended for the first-time config of the whitelist and ops.

...however, what you have noticed wasn't a known bug, but I may have missed some cases of first start  vs second start and attached volumes.

How are you starting the container when you observe the WHITELIST and OPS not taking effect?

**Comment by larrywright** [comment]
I'm using this docker-compose file:

```
version: '2'
services:
  minecraft:
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "BUKKIT"
      VERSION: "1.10.2"
      WHITELIST: name1,name2
      OPS: name1,name2
      MODE: "creative"
      ENABLE_COMMAND_BLOCK: "true"
      ALLOW_NETHER: "true"
      FORCE_GAMEMODE: "false"
      HARDCORE: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      PVP: "true"
      MAX_PLAYERS: 10
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      MAX_BUILD_HEIGHT: 500
      VIEW_DISTANCE: 50
      VM_OPTS: "-Xmx512M -Xms512M"
      MOTD: "My Minecraft server"
    image: itzg/minecraft-server
    container_name: minecraft
    stdin_open: true
    restart: always
    volumes:
      - minecraft-data:/data

volumes:
  minecraft-data:

```

**Comment by itzg** [comment]
Hmm, it might be a Bukkit-specific issue since tweaking your compose to run a vanilla server on 25566 processed the ops and whitelist properly. Can you see if you can confirm the same using (but change `itzg` to yourself :) ):

```
version: '2'
services:
  minecraft:
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.10.2"
      WHITELIST: itzg
      OPS: itzg
      MODE: "creative"
      ENABLE_COMMAND_BLOCK: "true"
      ALLOW_NETHER: "true"
      FORCE_GAMEMODE: "false"
      HARDCORE: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      PVP: "true"
      MAX_PLAYERS: 10
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      MAX_BUILD_HEIGHT: 500
      VIEW_DISTANCE: 50
      VM_OPTS: "-Xmx512M -Xms512M"
      MOTD: "My Minecraft server"
    image: itzg/minecraft-server
    container_name: minecraft-vanilla
    stdin_open: true
    restart: always
    volumes:
      - minecraft-vanilla-data:/data

volumes:
  minecraft-vanilla-data:
```
